baseurl: "https://mvpotter.github.io/theuniversearound/"
theme: "hugo-bearblog"
title: "The Universe Around"
author: "Поттер Михаил"
languageCode: "ru-ru"
disqusShortname: "theuniversearound"
enableRobotsTXT: true
canonifyurls: true

params:
  hideMadeWithLine: false

author:
  name: "Поттер Михаил"
  email: "michaelpotter@mail.ru"
  twitter: "dude1366"

menu:
  main:
    - name: Email
      url: mailto:michaelpotter@mail.ru
    - name: Twitter
      url: https://twitter.com/dude1366
    - name: Telegram
      url: https://t.me/mvpotter
